"""initial migration

Revision ID: 88abbbb53bc9
Revises: 
Create Date: 2026-04-08 06:33:28.187282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88abbbb53bc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jenis_ekskul',
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelas',
    sa.Column('tingkat', sa.Integer(), nullable=False),
    sa.Column('nama_tingkat', sa.String(length=20), nullable=False),
    sa.Column('fase', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tingkat')
    )
    op.create_table('mapel',
    sa.Column('kode', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kelompok', sa.String(length=10), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.Column('status_aktif', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sekolah',
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('npsn', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('kode_pos', sa.String(length=10), nullable=True),
    sa.Column('desa_kelurahan', sa.String(length=50), nullable=True),
    sa.Column('kecamatan', sa.String(length=50), nullable=True),
    sa.Column('kabupaten_kota', sa.String(length=50), nullable=True),
    sa.Column('provinsi', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('kepala_sekolah', sa.String(length=100), nullable=True),
    sa.Column('nip_kepala_sekolah', sa.String(length=30), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npsn')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('tahun_ajaran',
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.Column('status_aktif', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('semester',
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.Column('status_aktif', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('guru',
    sa.Column('nip', sa.String(length=30), nullable=True),
    sa.Column('nuptk', sa.String(length=30), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('agama', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('status_aktif', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nuptk'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('guru', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guru_nip'), ['nip'], unique=True)

    op.create_table('siswa',
    sa.Column('nisn', sa.String(length=20), nullable=True),
    sa.Column('nis', sa.String(length=20), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=50), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('agama', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('nama_ayah', sa.String(length=100), nullable=True),
    sa.Column('nama_ibu', sa.String(length=100), nullable=True),
    sa.Column('pekerjaan_ayah', sa.String(length=50), nullable=True),
    sa.Column('pekerjaan_ibu', sa.String(length=50), nullable=True),
    sa.Column('alamat_orang_tua', sa.Text(), nullable=True),
    sa.Column('no_hp_orang_tua', sa.String(length=20), nullable=True),
    sa.Column('status_aktif', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_siswa_nis'), ['nis'], unique=True)
        batch_op.create_index(batch_op.f('ix_siswa_nisn'), ['nisn'], unique=True)

    op.create_table('catatan_wali_kelas',
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nilai_ekskul',
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('ekskul_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('predikat', sa.String(length=2), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ekskul_id'], ['jenis_ekskul.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapor',
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('tanggal_terbit', sa.Date(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rombel',
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('wali_kelas_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['tahun_ajaran.id'], ),
    sa.ForeignKeyConstraint(['wali_kelas_id'], ['guru.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absensi',
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('rombel_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('sakit', sa.Integer(), nullable=True),
    sa.Column('izin', sa.Integer(), nullable=True),
    sa.Column('alfa', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rombel_id'], ['rombel.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anggota_rombel',
    sa.Column('rombel_id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rombel_id'], ['rombel.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mengajar',
    sa.Column('guru_id', sa.Integer(), nullable=False),
    sa.Column('mapel_id', sa.Integer(), nullable=False),
    sa.Column('rombel_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guru_id'], ['guru.id'], ),
    sa.ForeignKeyConstraint(['mapel_id'], ['mapel.id'], ),
    sa.ForeignKeyConstraint(['rombel_id'], ['rombel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nilai',
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('mengajar_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('nilai_formatif', sa.Float(), nullable=True),
    sa.Column('nilai_sumatif', sa.Float(), nullable=True),
    sa.Column('nilai_pts', sa.Float(), nullable=True),
    sa.Column('nilai_pas', sa.Float(), nullable=True),
    sa.Column('nilai_akhir', sa.Float(), nullable=True),
    sa.Column('predikat', sa.String(length=2), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('status_final', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mengajar_id'], ['mengajar.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.ForeignKeyConstraint(['siswa_id'], ['siswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nilai')
    op.drop_table('mengajar')
    op.drop_table('anggota_rombel')
    op.drop_table('absensi')
    op.drop_table('rombel')
    op.drop_table('rapor')
    op.drop_table('nilai_ekskul')
    op.drop_table('catatan_wali_kelas')
    with op.batch_alter_table('siswa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_siswa_nisn'))
        batch_op.drop_index(batch_op.f('ix_siswa_nis'))

    op.drop_table('siswa')
    with op.batch_alter_table('guru', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guru_nip'))

    op.drop_table('guru')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('semester')
    op.drop_table('tahun_ajaran')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    op.drop_table('sekolah')
    op.drop_table('roles')
    op.drop_table('mapel')
    op.drop_table('kelas')
    op.drop_table('jenis_ekskul')
    # ### end Alembic commands ###
